server.port=8085
spring.application.name=payment-service
spring.data.mongodb.uri=mongodb+srv://syodrAdmin:Swethaswethaswe@syodra-cluster.6vvkbfz.mongodb.net/ecommerce_payment_db?retryWrites=true&w=majority&appName=Syodra-Cluster
spring.data.mongodb.database=ecommerce_payment_db