server.port=8086
spring.application.name=search-service
spring.data.mongodb.uri=mongodb+srv://syodrAdmin:Swethaswethaswe@syodra-cluster.6vvkbfz.mongodb.net/ecommerce_search_db?retryWrites=true&w=majority&appName=Syodra-Cluster
spring.data.mongodb.database=ecommerce_search_db