server.port=8084
spring.application.name=order-service
spring.data.mongodb.uri=mongodb+srv://syodrAdmin:Swethaswethaswe@syodra-cluster.6vvkbfz.mongodb.net/ecommerce_order_db?retryWrites=true&w=majority&appName=Syodra-Cluster
spring.data.mongodb.database=ecommerce_order_db