server.port=8082
spring.application.name=inventory-service
spring.data.mongodb.uri=mongodb+srv://syodrAdmin:Swethaswethaswe@syodra-cluster.6vvkbfz.mongodb.net/ecommerce_inventory_db?retryWrites=true&w=majority&appName=Syodra-Cluster
spring.data.mongodb.database=ecommerce_inventory_db