server.port=8083
spring.application.name=cart-service
spring.data.mongodb.uri=mongodb+srv://syodrAdmin:Swethaswethaswe@syodra-cluster.6vvkbfz.mongodb.net/ecommerce_cart_db?retryWrites=true&w=majority&appName=Syodra-Cluster
spring.data.mongodb.database=ecommerce_cart_db